### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by moodyblue** [Fish2/PlexConnect#8]
Hi, and thanks for maintaining a fork that enhances PlexConnect. As you may know, I am a Ninja in the Plex Forums, and as such I have some contacts with Plex development. Unfortunately my programming skills are very limited with today's tools (I've learned programming 47 years ago, I can still understand the code but programming is another story...).

Do you think that the changes that you are implementing can be of general use ? If yes, maybe I can help pushing them to wider audiences. And there is another folk that is available to continue development, if needed. What do you think ?

**Comment by Fish2** [comment]
Hi @moodyblue im not the best i am mainly self tort but can read and make changes to many languages much like you. At the moment i have 2 other branches which are very work in progress and i don't get much time to work on them. Most of the work i do is more optimisation which are generally simpler to add and change. I can keep a stable brach and try and keep it always up to date and working. But i can't do it alone I can definitely keep an eye on issues and also would be able to look and implement peoples pull requests. To keep a more active plexconnect. I also would be happy to add some Collaborators to my fork which would also help keep plexconnect up to date and to make sure pull requests and issues get dealt with in good time. I mainly have this fork for my use and my plexconnect docker container points to it. At the moment it is running very stable and use used most days.

**Comment by moodyblue** [comment]
I've created a channel in Slack so that we can duscuss

https://join.slack.com/t/plexconnect2/shared_invite/enQtMjkzMzkyNjI4MjI4LWFlOTRjNzE4YTY5NjQ2ZTZmM2RjYzczM2NmN2UzZDY2ZDVjNjg0NThkMWYwZTQ4MDE3NTg4YTMxZWViM2IyODc
